spring:
  application:
    name: cluster-example
  redis:
    host: localhost
    port: 6379
    database: 0
  hazelcast:
    addresses: ["127.0.0.1"]

dew:
  cluster:
    cache: redis
    dist: hazelcast # 可选 redis/hazelcast
    mq: hazelcast # 可选 redis/hazelcast

logging:
  path: ./logs