spring:
  application:
    name: cluster-example
  redis:
    host: redis.fengdai.org
    port: 6379
    database: 0
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 1
      min-idle: 0
    password: tairan2017@
  rabbitmq:
    host: mq.fengdai.org
    port: 5672
    username: guest
    password: guest
  hazelcast:
    addresses: ["127.0.0.1"]

dew:
  cluster:
    cache: redis
    dist: redis # 可选 redis/hazelcast
    mq: redis # 可选 redis/hazelcast/rabbit
    election: eureka

# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

logging:
  path: ./logs