dew:
  cloud:
    error:
      notify-interval-sec: 10
      notify-emails: 71964899@qq.com
#      enabled: true
      #notify-event-types: FAILURE,SHORT_CIRCUITED
      #notify-include-keys: ["ExampleClient#deleteExe(int,String)","ExampleClient#postExe(int,String)"]
spring:
  mail:
    host: smtp.alibaba.com
    username: jiangji@tairanchina.com
    password: gSQiQxGR5wLUFkNh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: fasle
  application:
    name: hystrix-feign-example2
server:
  tomcat:
    max-threads: 300
  port: 12000
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone:  http://registry:123456@localhost:9999/eureka
ribbon:
  PoolMaxThreads: 12
  OkToRetryOnAllOperations: false
  ConnectTimeout: 1000
  ReadTimeout: 2000000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 2

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      fallback:
        enabled: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500000
  threadpool:
    default:
      allowMaximumSizeToDivergeFromCoreSize: true
      maximumSize: 300
