spring:
  application:
    name: zipkin-service-example

server:
  port: 8892

dew:
  basic:
    name: zipkin-service
    version: 1.0
    desc: desc
    web-site: www.tairanchina.com
    doc:
      base-package: com.tairanchina

logging:
  path: ./logs

com:
  zipkin:
    serviceName: service2
    url: http://192.168.111.224:9411
    connectTimeout: 500
    readTimeout: 500
    flushInterval: 1
    compressionEnabled: true
