spring:
  application:
    name: hystrix-example
  redis:
    host: localhost
    port: 6379
    database: 0

server:
  port: 11000

eureka:
  client:
    serviceUrl:
      defaultZone:  http://registry:123456@localhost:9999/eureka

dew:
  cluster:
    cache: redis
