spring:
  application:
    name: monitor-example
  cloud:
    config:
      enabled: false
  boot:
    admin:
      url: http://localhost:12000

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:123456@localhost:10000/eureka

logging:
  path: ./logs
