spring:
  application:
    name: thrift-service-example

server:
  port: 8890

dew:
  basic:
    name: thrift-service-example
    version: 1.0
    desc: desc
    web-site: www.tairanchina.com
    doc:
      base-package: com.tairanchina

logging:
  path: ./logs

thrift:
  client:
      maxThread: 10 # pool object num,default is ten
  service:
      connectTimeout: 2000
      readTimeout: 50000
      maxRetries: 3 #if in cloud env,should be set empty,if not,should be set a fixed address
      endpoint: # if in cloud env,should be set empty,if not,should be set a fixed address

eureka:
  client:
    serviceUrl:
      defaultZone:  http://tr:123456@172.30.248.162:10000/eureka
