spring:
  application:
    name: thrift-service-example

server:
  port: 8890

dew:
  basic:
    name: thrift-service-example
    version: 1.0
    desc: desc
    web-site: www.tairanchina.com
    doc:
      base-package: com.tairanchina

logging:
  path: ./logs

bbthriftserver:
  connectTimeout: 3000
  readTimeout: 3000
  maxRetries: 1 # if call fail,it will try to recall times
  endpoint:   # if in cloud env,should be set empty,if not,should be set a fixed address

thrift:
  client:
    max:
      poolobject: 10 # pool object num,default is ten

eureka:
  client:
    serviceUrl:
      defaultZone:  http://tr:123456@172.30.248.162:10000/eureka