spring:
  application:
    name: pet-store # 项目名称，对Spring Cloud而言也是service-id
  datasource: # 数据库连接信息
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:petstore;MODE=MySQL
  redis: # Redis连接信息
    host: localhost
    port: 6379
    database: 0

server: # http端口号
  port: 8080

dew:
  basic:
    name: pet-store
    version: 1.0
    desc: 宠物商店
    web-site:
    doc:
      basePackage: your.group.controller # API文档路径
  cluster:
    cache: redis # 指定集群缓存实现为redis
  jdbc:
    base-packages: ["your.group.jdbc"]