dew:
  cloud:
    error:
      notify-interval-sec: 10000
      notify-emails:
      notify-event-types: FAILURE,SHORT_CIRCUITED
      notify-include-keys: ["ExampleClient#deleteExe(int,String)","ExampleClient#postExe(int,String)"]
spring:
  mail:
    host: smtp.163.com
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: hystrix-feign-example
server:
  port: 11000
eureka:
  client:
    fetch-registry: true #必须加？关闭自我保护模式
    serviceUrl:
      defaultZone:  http://registry:123456@localhost:10000/eureka
ribbon:
  ReadTimeout: 3000
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      fallback:
        enabled: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
