spring:
  application:
    name: dubbo-example

  dubbo:
    application:
      name: dubbo-example
    protocol:
      name: dubbo
      port: -1
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: com.tairanchina.csp.dew.example
    monitor:
      protocol: registry

  datasource:
    driver-class-name: org.h2.Driver
    url: ds:h2:mem:test

server:
  port: 8080

logging:
  path: ./logs