dew:
  basic:
    name: Dew服务框架
    version: 1.0
    desc:
    webSite: www.tairanchina.com
    doc:
      basePackage: "com.tairanchina"
  cluster:
    cache: redis
    dist: hazelcast
    mq: hazelcast

spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 24000
  mail:
    host: smtp.exmail.qq.com
    username: test@ecfront.com
    password: Ez1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
eureka:
  instance:
    metadata-map:
      cluster: dew

logging:
  path: ./logs

management:
  address: 127.0.0.1

