dew:
  basic:
    name: Dew服务框架
    version: 1.0
    desc:
    webSite: www.tairanchina.com
    doc:
      base-packages: ["com.tairanchina"]
  cluster:
    cache: redis
    dist: redis
    mq: redis

spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 24000

eureka:
  instance:
    metadata-map:
      cluster: dew

logging:
  path: ./logs

management:
  address: 127.0.0.1
  security:
    enabled: false

